// Base document type (auto-generated by bkend.ai)
export interface BaseDocument {
  id: string;
  createdAt: string;
  updatedAt: string;
}

// User roles
export type UserRole = 'admin' | 'member';

// User
export interface User extends BaseDocument {
  email: string;
  name: string;
  role: UserRole;
  profileImage?: string;
  teamId?: string;
}

// Team
export interface Team extends BaseDocument {
  name: string;
  description?: string;
  adminId: string;
  memberIds: string[];
  inviteCode: string;
}

// Shared file/resource
export interface SharedFile extends BaseDocument {
  teamId: string;
  uploaderId: string;
  uploaderName: string;
  title: string;
  description?: string;
  fileUrl: string;
  fileType: 'image' | 'document' | 'video' | 'other';
  fileName: string;
  fileSize: number;
  tags: string[];
}

// Chat message
export interface ChatMessage extends BaseDocument {
  teamId: string;
  senderId: string;
  senderName: string;
  content: string;
  type: 'text' | 'image' | 'file';
  fileUrl?: string;
  readBy: string[];
}

// Action types (카톡 킬러 기능 - 메시지 속성 변환)
export type ActionType = 'todo' | 'decision' | 'idea';
export type ActionStatus = 'open' | 'in_progress' | 'done';

export interface ActionItem extends BaseDocument {
  teamId: string;
  sourceMessageId: string;
  creatorId: string;
  assigneeId?: string;
  actionType: ActionType;
  title: string;
  content: string;
  status: ActionStatus;
  dueDate?: string;
  tags: string[];
}

// Team member (User + team role context)
export interface TeamMember {
  id: string;
  name: string;
  email: string;
  profileImage?: string;
  isAdmin: boolean;
  joinedAt: string;
}

// Auth response from bkend.ai
export interface AuthResponse {
  accessToken: string;
  refreshToken: string;
  tokenType: string;
  expiresIn: number;
}

// Notification types
export type NotificationType = 'chat' | 'file' | 'action' | 'team' | 'deadline';

export interface Notification extends BaseDocument {
  teamId: string;
  recipientId: string;
  type: NotificationType;
  title: string;
  body: string;
  link?: string;
  isRead: boolean;
  sourceId?: string;
}
